In [93]:
from setup import *
from random import random
import pandas as pd
import numpy as np

df = pd.read_csv('last_guidebook.csv')
jf = pd.read_csv('judge_merge.csv')
pf = pd.read_csv('project_merge.csv')
display(df)
# display(df.loc[df['Question Text']=='Feedback/Comments'])

,Device ID,Session/Item ID,Session/Item Name,Question ID,Question Text,Response,Date
0,17224511,8786683,"Bedekar, Himani",157036,Poster Content,10: exceptional,November 03 2017 03:51PM
1,17224511,8786664,"Potluri, Sai Pradeep",157036,Poster Content,10: exceptional,November 03 2017 02:23PM
2,17204425,8786847,"Marble, Kassie",157036,Poster Content,7: above average,November 03 2017 12:21PM
3,17204425,8786681,"Louis, Pierry",157036,Poster Content,6: slightly above average,November 03 2017 12:15PM
4,17204425,8786846,"Nsekpong, Tyler",157036,Poster Content,7: above average,November 03 2017 12:09PM
5,17206520,8786804,"Morris , Madeleine",157036,Poster Content,4: slightly below average,November 03 2017 12:09PM
6,17206520,8786822,"Gonzales , Jannelle",157036,Poster Content,3: less than average,November 03 2017 12:08PM
7,17206368,8786842,"Bernet, Frederick",157036,Poster Content,5: average,November 03 2017 12:08PM
8,17206520,8786812,"Parra, Victoria",157036,Poster Content,3: less than average,November 03 2017 12:08PM
9,17205792,8786675,"Guzman, Carlos",157036,Poster Content,8: good,November 03 2017 12:07PM
10,17206368,8786842,"Bernet, Frederick",157036,Poster Content,5: average,November 03 2017 12:06PM
11,17206520,8786817,"Warford, Khira",157036,Poster Content,8: good,November 03 2017 12:06PM
12,17215906,8786658,"Pippins, Esther",157036,Poster Content,6: slightly above average,November 03 2017 12:05PM
13,17206368,8786838,"Chen, Mengzhe",157036,Poster Content,7: above average,November 03 2017 12:03PM
14,17214793,8786838,"Chen, Mengzhe",157036,Poster Content,7: above average,November 03 2017 12:01PM
15,17206368,8786613,"Idoko-Akoh, Ajogu",157036,Poster Content,7: above average,November 03 2017 11:59AM
16,17202743,8786580,"Long, Chonique",157036,Poster Content,8: good,November 03 2017 11:58AM
17,17207695,8786812,"Parra, Victoria",157036,Poster Content,6: slightly above average,November 03 2017 11:57AM
18,17205968,8786838,"Chen, Mengzhe",157036,Poster Content,9: great,November 03 2017 11:55AM
19,17205742,8786706,"McClinton, Trey",157036,Poster Content,9: great,November 03 2017 11:54AM
20,17204465,8786580,"Long, Chonique",157036,Poster Content,5: average,November 03 2017 11:52AM
21,17206516,8786838,"Chen, Mengzhe",157036,Poster Content,7: above average,November 03 2017 11:52AM
22,17206516,8786681,"Louis, Pierry",157036,Poster Content,2: poor,November 03 2017 11:49AM
23,17206516,8786681,"Louis, Pierry",157036,Poster Content,5: average,November 03 2017 11:48AM
24,17202743,8786821,"Whisenhunt, Samantha",157036,Poster Content,8: good,November 03 2017 11:43AM
25,17206400,8786587,"Sharma, Riya",157036,Poster Content,7: above average,November 03 2017 11:42AM
26,17204732,8786580,"Long, Chonique",157036,Poster Content,8: good,November 03 2017 11:40AM
27,17205754,8786658,"Pippins, Esther",157036,Poster Content,10: exceptional,November 03 2017 11:39AM
28,17207695,8786804,"Morris , Madeleine",157036,Poster Content,8: good,November 03 2017 11:38AM
29,17204732,8786586,"Timms, Edward",157036,Poster Content,7: above average,November 03 2017 11:36AM
...,...,...,...,...,...,...,...
4928,17195664,8909932,"Rudder, Earl",144457,Judges Password,score,November 01 2017 12:20PM
4929,17124099,8872019,NaN,144457,Judges Password,score,October 25 2017 04:58PM
4930,17124097,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:54PM
4931,17124097,8872014,NaN,144457,Judges Password,Score,October 25 2017 12:54PM
4932,17124097,8872015,NaN,144457,Judges Password,Score,October 25 2017 12:53PM
4933,17123091,8872017,NaN,144457,Judges Password,Score,October 25 2017 12:52PM
4934,17124097,8872016,NaN,144457,Judges Password,Score,October 25 2017 12:52PM
4935,17124097,8872017,NaN,144457,Judges Password,Score,October 25 2017 12:51PM
4936,17124097,8872018,NaN,144457,Judges Password,Score,October 25 2017 12:51PM
4937,17124098,8872019,NaN,144457,Judges Password,score,October 25 2017 12:48PM
4938,17124114,8872013,NaN,144457,Judges Password,score,October 25 2017 12:46PM
4939,17123091,8872016,NaN,144457,Judges Password,score,October 25 2017 12:42PM
4940,17123091,8872015,NaN,144457,Judges Password,score,October 25 2017 12:42PM
4941,17124297,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:41PM
4942,17124101,8872014,NaN,144457,Judges Password,Score,October 25 2017 12:40PM
4943,17123091,8872014,NaN,144457,Judges Password,score,October 25 2017 12:40PM
4944,17123091,8872013,NaN,144457,Judges Password,score,October 25 2017 12:35PM
4945,17124105,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:29PM
4946,17124114,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:19PM
4947,17124105,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:19PM
4948,17124102,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:18PM
4949,17124101,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:18PM
4950,17124099,8872013,NaN,144457,Judges Password,score,October 25 2017 12:18PM
4951,17123091,8872013,NaN,144457,Judges Password,score,October 25 2017 12:18PM
4952,17124098,8872013,NaN,144457,Judges Password,score,October 25 2017 12:18PM
4953,17124097,8872013,NaN,144457,Judges Password,Score,October 25 2017 12:18PM
4954,17124096,8872013,NaN,144457,Judges Password,score,October 25 2017 12:18PM
4955,17124095,8872013,NaN,144457,Judges Password,score,October 25 2017 12:18PM
4956,17124093,8872013,NaN,144457,Judges Password,score,October 25 2017 12:18PM
4957,17123091,8784599,NaN,144457,Judges Password,score,October 25 2017 10:40AM

In [99]:
def f_projects(grp):
    ret_df = grp.loc[grp['Question Text']=='Feedback/Comments']['Response'].reset_index(drop=True)
    return ret_df

newdf = df.groupby('Session/Item ID').apply(lambda g: len(g.loc[g['Question Text']=='Feedback/Comments'])).drop([8909932,8872013])
#apply(f_projects).drop([8909932,8872013])
display(newdf.loc[newdf>=4])

                 0
Session/Item ID
8786582          4
8786602          4
8786625          4
8786638          4
8786648          4
8786649          5
8786651          4
8786654          4
8786656          5
8786658          5
8786659          6
8786662          4
8786671          4
8786672          4
8786681          4
8786698          4
8786842          4

[17 rows x 1 columns]

In [60]:
merge_df = pd.read_csv('convert_df.csv')
display(merge_df)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 203: invalid start byte